import "@atomic-ai/tokens/css";
import "../styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Marketing Site</title>
        <meta name="description" content="Generated by Atomic AI" />
      </head>
      <body>{children}</body>
    </html>
  );
}

