export const termsData = {
  title: "Terms of Service",
  lastUpdated: "December 19, 2025",
  sections: [
    {
      id: "acceptance",
      title: "1. Acceptance of Terms",
      content: "By accessing and using OxyGen AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service."
    },
    {
      id: "use-of-service",
      title: "2. Use of Service",
      content: "You agree to use OxyGen AI only for lawful purposes and in accordance with these Terms. You agree not to use the service to generate content that is illegal, harmful, or violates any third-party rights."
    },
    {
      id: "accounts",
      title: "3. User Accounts",
      content: "You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate these terms."
    },
    {
      id: "subscriptions",
      title: "4. Subscriptions and Billing",
      content: "Subscriptions are billed monthly or annually in advance. All fees are non-refundable except as required by law. You may cancel your subscription at any time, and it will remain active until the end of your billing period."
    },
    {
      id: "intellectual-property",
      title: "5. Intellectual Property",
      content: "The code and components generated by OxyGen AI belong to you. You own all rights to the generated output. However, the OxyGen AI platform, its design, and underlying technology remain our intellectual property."
    },
    {
      id: "limitations",
      title: "6. Service Limitations",
      content: "OxyGen AI is provided 'as is' without warranties of any kind. We do not guarantee uninterrupted or error-free service. Build credits expire at the end of each billing period and do not roll over."
    },
    {
      id: "liability",
      title: "7. Limitation of Liability",
      content: "To the maximum extent permitted by law, OxyGen AI shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the service."
    },
    {
      id: "termination",
      title: "8. Termination",
      content: "We reserve the right to terminate or suspend your account and access to the service immediately, without prior notice, for conduct that we believe violates these Terms or is harmful to other users."
    },
    {
      id: "changes",
      title: "9. Changes to Terms",
      content: "We reserve the right to modify these Terms at any time. We will notify users of any material changes via email or through the service. Continued use after changes constitutes acceptance."
    },
    {
      id: "contact",
      title: "10. Contact Information",
      content: "If you have any questions about these Terms, please contact us at legal@oxygenai.com"
    }
  ]
} as const

