"use client";

import { ConfigProvider } from "antd";
import { antdTheme } from "@atomic-ai/tokens/antd";
import { setAdapter } from "@atomic-ai/ui";
import { useEffect } from "react";
import "@atomic-ai/tokens/css";
import "../styles/globals.css";

// Set adapter to antd for ERP site
useEffect(() => {
  setAdapter("antd");
}, []);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>ERP Dashboard</title>
        <meta name="description" content="Generated by Atomic AI" />
      </head>
      <body>
        <ConfigProvider theme={antdTheme}>{children}</ConfigProvider>
      </body>
    </html>
  );
}

